# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensorrand = torch.rand(7,7)
tensorrand

tensor([[0.2182, 0.1389, 0.4975, 0.7701, 0.5501, 0.4337, 0.7899],
        [0.9670, 0.6243, 0.8240, 0.2127, 0.8251, 0.6729, 0.0869],
        [0.2345, 0.7118, 0.5491, 0.5689, 0.3662, 0.4519, 0.5309],
        [0.5490, 0.7306, 0.8797, 0.1430, 0.6057, 0.6996, 0.9256],
        [0.0662, 0.3369, 0.9104, 0.8051, 0.9667, 0.6084, 0.0191],
        [0.9261, 0.5079, 0.6306, 0.3906, 0.8708, 0.4440, 0.5530],
        [0.4136, 0.0476, 0.4225, 0.5836, 0.7213, 0.6848, 0.6029]])

In [4]:
tensorrand.shape

torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
tensorrand2 = torch.rand(1,7)
# Perform matrix multiplication

torch.matmul(tensorrand,tensorrand2.T)#T is the transpose

tensor([[1.8730],
        [1.8148],
        [1.6837],
        [2.2655],
        [1.2649],
        [2.1456],
        [1.8832]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed

torch.manual_seed(21)
# Create two random tensors
tensor1r = torch.rand(1,2)
tensor2r = torch.rand(2,1)

# Matrix multiply tensors

torch.matmul(tensor1r,tensor2r)

tensor([[0.0300]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [14]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)#sets the manual seed



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
!nvidia-smi

# Create two random tensors on GPU

tensor1r =torch.rand(2,3)
tensor2r = torch.rand(2,3)

print(tensor1r)
print(tensor2r)

Mon Apr  8 22:05:01 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [17]:
# Perform matmul on tensor_A and tensor_B

tensormult1 = torch.matmul(tensor1r,tensor2r.T)
tensormult1

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [19]:
# Find max

print(tensormult1.max())

# Find min
print(tensormult1.min())

tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [20]:
# Find arg max
print(tensormult1.argmax())

# Find arg min

print(tensormult1.argmin())

tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
torch.manual_seed(7)

# Create random tensor
torch_ten_1 = torch.rand(1,1,1,10)


# Remove single dimensions
torch_ten_1_res = torch_ten_1[0,0,0,:]

# Print out tensors and their shapes

print(torch_ten_1,torch_ten_1.shape)
print(torch_ten_1_res,torch_ten_1_res.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
